name: Build

on:
  push:
    branches: master

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Apply Patches and Build
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          ./gradlew clean build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.timestamp.outputs.repo_name }}-${{ steps.timestamp.outputs.short_sha }}
          path: target/*.jar
      - name: Get timestamp and short SHA
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=repo_name::$(echo ${{ github.repository }} | cut -d'/' -f2)"
      - name: Automatic release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.timestamp.outputs.timestamp }}"
          prerelease: false
          title: "${{ steps.timestamp.outputs.repo_name }}-${{ steps.timestamp.outputs.short_sha }} Release"
          files: |
            target/*.jar
